version: 2.1
jobs:
  build_demo:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run: ./gradlew demo:assemble
      - store_artifacts:
          path: demo/build/outputs/apk/debug
          destination: binaries
  build_library:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run: ./gradlew library:assemble
      - store_artifacts:
          path: library/build/outputs/aar
          destination: binaries
      - persist_to_workspace:
          root: .
          paths:
            - library/build/outputs/aar
  ensure_release_allowed:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: ./_scripts/ensure_release_allowed.sh
  release_on_github:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run: ./gradlew demo:assembleDebug
      - attach_workspace:
          at: .
      - run: ./_scripts/release_github.sh
  release_library_on_central:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Decript GPG secret keyring
          command: openssl aes-256-cbc -md sha512 -iter 100000 -d -in secring.gpg.enc -out secring.gpg -k $GPG_SECRET_DECRIPTION_KEY
          when: always
      - run:
          name: Upload library to Maven Central
          command: ./gradlew :library:publishLibraryPublicationToSonatypeRepository --no-daemon --no-build-cache --refresh-dependencies
          when: always
      - run:
          name: Close and release staging repository in Nexus
          command: ./gradlew closeAndReleaseRepository
          when: always
workflows:
  version: 2.1
  check:
    jobs:
      - build_demo
      - build_library
  release:
    jobs:
      - build_library:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - ensure_release_allowed:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release_on_github:
          context: onautoscrolledtoview_release_github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - ensure_release_allowed
            - build_library
      - release_library_on_central:
          context: test-accessors_release_mavencentral
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - ensure_release_allowed
            - build_library
